driver:
  name: docker
  use_sudo: false
  privileged: true
  forward:
    - 80

platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: ubuntu-16.04
  - name: debian-8
  - name: debian-9

suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -X -p git stable 2017.7
  - name: carbon
    provisioner:
      salt_bootstrap_options: -X -p git stable 2016.11

provisioner:
  name: salt_solo
  salt_install: bootstrap
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - .git
  state_top:
    base:
      "*":
        - dhcpd
        - dhcpd.config
        - dhcpd.test
  pillars:
    top.sls:
      base:
        "*":
          - dhcpd
          - test
    test.sls:
      dhcpd:
        testing: true
  pillars-from-files:
    dhcpd.sls: pillar.example
